name: dbt prod build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt
        run: pip install dbt-snowflake==1.11.3

      - name: Install dbt packages
        run: dbt deps
        working-directory: ./

      - name: Run dbt build
        run: dbt build --profiles-dir prod --target prod
        working-directory: ./
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DBT_ENV_NAME: PROD

      - name: Upload manifest
        uses: actions/upload-artifact@v4
        with:
          name: prod-manifest
          path: target-prod/manifest.json